### PR TITLE
Lm01/master

### PR DESCRIPTION
**Pull request by payne-chris-r**

### CODE REVIEW

**Comment by jrhorn424** [comment]
@payne-chris-r @raq929 Do we have a solution PR fo this?

**Comment by payne-chris-r** [comment]
No new solution, because it's very different from the `013/training` branch. I'm currently building out a `tutorial` branch from @gaand's commit history because !pods, but I didn't finish over the weekend like I had hoped. My goal (which probably won't happen before weds, but will certainly happen before it's delivered for `lm01` is to complete the `tutorial` and thought I would squash that into a solution branch when I'm done?

**Comment by raq929** [comment]
@payne-chris-r can you push that branch ASAP? I will finish it.

**Comment by payne-chris-r** [comment]
https://github.com/ga-wdi-boston/ember-resources/tree/tutorial

**Comment by raq929** [comment]
You did not fix the issues! 🔨

**Pull request merged**
